import streamlit as st
from groq import Groq
import requests
from PIL import Image
from io import BytesIO

# --- Page Configuration ---
st.set_page_config(page_title="Alpha AI Pro", page_icon="🚀", layout="wide")

# --- Styling ---
st.markdown("""
    <style>
    .stChatMessage { border-radius: 15px; margin-bottom: 10px; }
    .stChatInput { border-radius: 20px; }
    </style>
    """, unsafe_allow_html=True)

# --- Secrets & Clients ---
GROQ_API_KEY = st.secrets["GROQ_API_KEY"]
client = Groq(api_key=GROQ_API_KEY)

OWNER_NAME = "Hasith"
AI_NAME = "Alpha"

# --- Functions ---
def generate_image(prompt):
    """Pollinations API """
    image_url = f"https://image.pollinations.ai/prompt/{prompt.replace(' ', '%20')}?width=1024&height=1024&nologo=true"
    return image_url

# --- Sidebar ---
with st.sidebar:
    st.title(f"⚙️ {AI_NAME} Control Panel")
    st.info(f"Created by: **{OWNER_NAME}**")
    model_option = st.selectbox("Choose Model", ["llama-3.3-70b-versatile", "llama3-8b-8192"])
    if st.button("Clear Chat History"):
        st.session_state.messages = []
        st.rerun()

# --- Chat Logic ---
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display messages
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        if "image_url" in message:
            st.image(message["image_url"], caption="Generated by Alpha")
        else:
            st.markdown(message["content"])

# User Input
if prompt := st.chat_input("Ask Alpha anything (or type 'imagine a...')"):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        # Image Generation Logic
        if prompt.lower().startswith(("imagine", "generate image", "පින්තූරයක් හදන්න")):
            with st.spinner("🎨 Designing your imagination..."):
                img_url = generate_image(prompt)
                st.image(img_url, caption="Your AI Masterpiece")
                st.session_state.messages.append({"role": "assistant", "image_url": img_url})
        
        # Text Generation Logic (Streaming)
        else:
            stream = client.chat.completions.create(
                messages=[
                    {"role": "system", "content": f"You are {AI_NAME}, an advanced AI built by {OWNER_NAME}. You are witty, helpful, and highly intelligent."},
                    *[{"role": m["role"], "content": m["content"]} for m in st.session_state.messages]
                ],
                model=model_option,
                temperature=0.7,
                stream=True,
            )
            
            response = st.write_stream(stream)
            st.session_state.messages.append({"role": "assistant", "content": response})
