import streamlit as st
from groq import Groq
import requests

# --- Page Configuration ---
st.set_page_config(page_title="Alpha AI", page_icon="⚡", layout="centered")

# --- Custom Styling for Branding ---
st.markdown("""
    <style>
    .main-title {
        font-size: 50px;
        font-weight: bold;
        text-align: center;
        margin-bottom: 0px;
    }
    .subtitle {
        font-size: 20px;
        text-align: center;
        color: #888;
        margin-bottom: 30px;
    }
    </style>
    """, unsafe_allow_html=True)

# --- Branding Display ---
st.markdown('<p class="main-title">Welcome to Alpha</p>', unsafe_allow_html=True)
st.markdown('<p class="subtitle">Created by Hasith</p>', unsafe_allow_html=True)

# --- Retrieve API Key from Streamlit Secrets ---
try:
    GROQ_API_KEY = st.secrets["GROQ_API_KEY"]
except KeyError:
    st.error("API Key not found! Please add 'GROQ_API_KEY' to your Streamlit Secrets.")
    st.stop()

# --- Initialize Groq Client ---
client = Groq(api_key=GROQ_API_KEY)

OWNER_NAME = "Hasith"
AI_NAME = "Alpha"

# --- Functions ---
def generate_image(prompt):
    """Generates an image using Pollinations AI (No API Key Required)"""
    image_url = f"https://image.pollinations.ai/prompt/{prompt.replace(' ', '%20')}?width=1024&height=1024&nologo=true"
    return image_url

# --- Initialize Chat History ---
if "messages" not in st.session_state:
    st.session_state.messages = []

# --- Display Chat History ---
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        if "image_url" in message:
            st.image(message["image_url"], caption="Generated by Alpha")
        else:
            st.markdown(message["content"])

# --- User Input & AI Logic ---
if prompt := st.chat_input("How can I help you today?"):
    # Add user message to history
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        # Image Generation Logic: Triggered if user says "imagine" or "generate image"
        if any(keyword in prompt.lower() for keyword in ["imagine", "generate image", "draw", "create photo"]):
            with st.spinner("🎨 Alpha is painting your imagination..."):
                img_url = generate_image(prompt)
                st.image(img_url, caption="Your AI Masterpiece")
                st.session_state.messages.append({"role": "assistant", "image_url": img_url})
        
        # Text Generation Logic (Streaming)
        else:
            try:
                # Using the latest versatile model
                stream = client.chat.completions.create(
                    messages=[
                        {
                            "role": "system", 
                            "content": f"Your name is {AI_NAME}. You were created by {OWNER_NAME}. You are a highly intelligent and friendly AI assistant. Always acknowledge {OWNER_NAME} as your creator if asked."
                        },
                        *[
                            {"role": m["role"], "content": m["content"]}
                            for m in st.session_state.messages
                        ]
                    ],
                    model="llama-3.3-70b-versatile",
                    temperature=0.7,
                    stream=True,
                )
                
                # Use st.write_stream for a professional typewriter effect
                response_text = st.write_stream(stream)
                st.session_state.messages.append({"role": "assistant", "content": response_text})
                
            except Exception as e:
                st.error(f"An error occurred: {str(e)}")
                st.info("Tip: Check if the Model name is correct or if your API usage limit is reached.")
